apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cooking-with-gas5-hpa
  labels:
    app: cooking-with-gas5
    version: 0.0.1
    backstage.io/kubernetes-id: cooking-with-gas5
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: cooking-with-gas5
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75